use anyhow::Result;
use std::env;

use crate::key_manager::KeyManager;
use crate::encrypted_vault::EncryptedVault;

/// Master keypair for the platform
#[derive(Debug, Clone)]
pub struct MasterKeypair {
    pub public_key: String,
    pub secret_key: String,
    pub network: String,
}

impl MasterKeypair {
    /// Generate a new master keypair
    pub fn generate(network: &str) -> Result<Self> {
        // In production, this would use Stellar SDK to generate keypair
        // For now, validate that the network is valid
        if network != "testnet" && network != "mainnet" {
            anyhow::bail!("Invalid network: {}", network);
        }

        Ok(Self {
            public_key: String::new(), // Would be generated by Stellar SDK
            secret_key: String::new(),
            network: network.to_string(),
        })
    }

    /// Validate keypair format
    pub fn validate(&self) -> Result<()> {
        KeyManager::validate_public_key(&self.public_key)?;
        KeyManager::validate_secret_key(&self.secret_key)?;
        Ok(())
    }

    /// Store master keypair in encrypted vault
    pub fn store_in_vault(&self, vault: &mut EncryptedVault) -> Result<()> {
        vault.store_secret_key("master_secret_key", &self.secret_key)?;
        vault.store_public_key("master_public_key", &self.public_key)?;
        Ok(())
    }

    /// Load master keypair from vault
    pub fn load_from_vault(vault: &EncryptedVault) -> Result<Self> {
        let public_key = vault.retrieve_public_key("master_public_key")?;
        let secret_key = vault.retrieve_secret_key("master_secret_key")?;
        let network = env::var("SOROBAN_NETWORK").unwrap_or_else(|_| "testnet".to_string());

        Ok(Self {
            public_key,
            secret_key,
            network,
        })
    }

    /// Display keypair safely (masked)
    pub fn display_safe(&self) {
        println!("🔑 Master Keypair");
        println!("━━━━━━━━━━━━━━━━");
        println!("Public Key: {}", self.public_key);
        println!("Secret Key: {}...{}", 
            &self.secret_key[..4], 
            &self.secret_key[self.secret_key.len() - 4..]
        );
        println!("Network: {}", self.network);
    }
}

/// Distribution account linked to issuing account
#[derive(Debug, Clone)]
pub struct DistributionAccount {
    pub public_key: String,
    pub secret_key: String,
    pub issuing_public_key: String,
    pub network: String,
}

impl DistributionAccount {
    /// Generate a new distribution account
    pub fn generate(network: &str, issuing_public_key: &str) -> Result<Self> {
        // In production, this would use Stellar SDK to generate keypair
        KeyManager::validate_public_key(issuing_public_key)?;

        Ok(Self {
            public_key: String::new(), // Generated by Stellar SDK
            secret_key: String::new(),
            issuing_public_key: issuing_public_key.to_string(),
            network: network.to_string(),
        })
    }

    /// Store distribution account in vault
    pub fn store_in_vault(&self, vault: &mut EncryptedVault) -> Result<()> {
        vault.store_secret_key("distribution_secret_key", &self.secret_key)?;
        vault.store_public_key("distribution_public_key", &self.public_key)?;
        vault.store_public_key("distribution_issuing_key", &self.issuing_public_key)?;
        Ok(())
    }

    /// Load distribution account from vault
    pub fn load_from_vault(vault: &EncryptedVault) -> Result<Self> {
        let public_key = vault.retrieve_public_key("distribution_public_key")?;
        let secret_key = vault.retrieve_secret_key("distribution_secret_key")?;
        let issuing_public_key = vault.retrieve_public_key("distribution_issuing_key")?;
        let network = env::var("SOROBAN_NETWORK").unwrap_or_else(|_| "testnet".to_string());

        Ok(Self {
            public_key,
            secret_key,
            issuing_public_key,
            network,
        })
    }

    /// Validate distribution account setup
    pub fn validate(&self) -> Result<()> {
        KeyManager::validate_public_key(&self.public_key)?;
        KeyManager::validate_public_key(&self.issuing_public_key)?;
        KeyManager::validate_secret_key(&self.secret_key)?;

        if self.public_key == self.issuing_public_key {
            anyhow::bail!("Distribution account must be different from issuing account");
        }

        Ok(())
    }

    /// Display account safely (masked)
    pub fn display_safe(&self) {
        println!("💰 Distribution Account");
        println!("━━━━━━━━━━━━━━━━━━━━━");
        println!("Distribution Public Key: {}", self.public_key);
        println!("Issuing Public Key: {}", self.issuing_public_key);
        println!("Secret Key: {}...{}", 
            &self.secret_key[..4], 
            &self.secret_key[self.secret_key.len() - 4..]
        );
        println!("Network: {}", self.network);
    }
}

/// Account funding status
#[derive(Debug, Clone)]
pub struct AccountFunding {
    pub account_public_key: String,
    pub network: String,
    pub balance: f64,
    pub is_funded: bool,
}

impl AccountFunding {
    /// Create funding status checker
    pub fn new(account_public_key: &str, network: &str) -> Result<Self> {
        KeyManager::validate_public_key(account_public_key)?;

        Ok(Self {
            account_public_key: account_public_key.to_string(),
            network: network.to_string(),
            balance: 0.0,
            is_funded: false,
        })
    }

    /// Fund account on testnet
    pub fn fund_testnet(&mut self, amount: f64) -> Result<()> {
        if amount <= 0.0 {
            anyhow::bail!("Amount must be positive");
        }

        if self.network != "testnet" {
            anyhow::bail!("Can only fund testnet accounts via friendbot");
        }

        println!("💰 Funding account on testnet...");
        println!("Account: {}", self.account_public_key);
        println!("Amount: {} XLM", amount);

        // In production, call Stellar testnet friendbot API
        self.balance = amount;
        self.is_funded = true;

        println!("✅ Account funded successfully!");
        println!("Balance: {} XLM", self.balance);

        Ok(())
    }

    /// Display funding status
    pub fn display_status(&self) {
        println!("💵 Account Funding Status");
        println!("━━━━━━━━━━━━━━━━━━━━━━━");
        println!("Account: {}", self.account_public_key);
        println!("Network: {}", self.network);
        println!("Balance: {} XLM", self.balance);
        println!("Status: {}", if self.is_funded { "✅ Funded" } else { "⏳ Not Funded" });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_master_keypair_validate() {
        let keypair = MasterKeypair {
            public_key: "GBZXVMIRWXL5VZVKXWV2FGKYTQ5VV5VRNJYQVZKYWW3XYVYP3IXGKDU".to_string(),
            secret_key: "SBZXVMIRWXL5VZVKXWV2FGKYTQ5VV5VRNJYQVZKYWW3XYVYP3IXGKDU".to_string(),
            network: "testnet".to_string(),
        };
        assert!(keypair.validate().is_ok());
    }

    #[test]
    fn test_distribution_account_different_from_issuing() {
        let dist = DistributionAccount {
            public_key: "GBZXVMIRWXL5VZVKXWV2FGKYTQ5VV5VRNJYQVZKYWW3XYVYP3IXGKDU".to_string(),
            secret_key: "SBZXVMIRWXL5VZVKXWV2FGKYTQ5VV5VRNJYQVZKYWW3XYVYP3IXGKDU".to_string(),
            issuing_public_key: "GBZXVMIRWXL5VZVKXWV2FGKYTQ5VV5VRNJYQVZKYWW3XYVYP3IXGKDU".to_string(),
            network: "testnet".to_string(),
        };
        // Should fail because they're the same
        assert!(dist.validate().is_err());
    }

    #[test]
    fn test_account_funding_positive_amount() -> Result<()> {
        let mut funding = AccountFunding::new(
            "GBZXVMIRWXL5VZVKXWV2FGKYTQ5VV5VRNJYQVZKYWW3XYVYP3IXGKDU",
            "testnet"
        )?;
        funding.fund_testnet(100.0)?;
        assert!(funding.is_funded);
        assert_eq!(funding.balance, 100.0);
        Ok(())
    }

    #[test]
    fn test_account_funding_invalid_amount() -> Result<()> {
        let mut funding = AccountFunding::new(
            "GBZXVMIRWXL5VZVKXWV2FGKYTQ5VV5VRNJYQVZKYWW3XYVYP3IXGKDU",
            "testnet"
        )?;
        let result = funding.fund_testnet(-50.0);
        assert!(result.is_err());
        Ok(())
    }

    #[test]
    fn test_account_funding_mainnet_fails() -> Result<()> {
        let mut funding = AccountFunding::new(
            "GBZXVMIRWXL5VZVKXWV2FGKYTQ5VV5VRNJYQVZKYWW3XYVYP3IXGKDU",
            "mainnet"
        )?;
        let result = funding.fund_testnet(100.0);
        assert!(result.is_err());
        Ok(())
    }
}
