#!/usr/bin/env bash
# StellarAid Signing Request & Response Handler Examples
# This script demonstrates the complete signing workflow

set -e

echo "🌟 StellarAid Signing Request & Response Handler Examples"
echo "==========================================================="
echo ""

# Configuration
DONOR_ADDRESS="GBJCHUKZMTFSLOMNC2P4TS4VJJBTCYL3SDKW3KSMSGQUZ6EFLXVX77JVH"
CAMPAIGN_ID=1
DONATION_AMOUNT=5000000
ASSET="XLM"
MEMO="Supporting education initiative"

# Directories
SIGNING_REQUESTS_DIR="./signing_requests"
SIGNED_TXNS_DIR="./signed_transactions"

mkdir -p "$SIGNING_REQUESTS_DIR"
mkdir -p "$SIGNED_TXNS_DIR"

echo "📝 Example 1: Build a Donation Signing Request"
echo "=============================================="
echo ""
echo "Command:"
echo "  stellaraid-cli signing build-donation \\"
echo "    $DONOR_ADDRESS \\"
echo "    $CAMPAIGN_ID \\"
echo "    $DONATION_AMOUNT \\"
echo "    $ASSET \\"
echo "    \"$MEMO\""
echo ""
echo "Expected Output:"
echo "  📝 Signing Request"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ID:          req_1234567890000"
echo "  Network:     testnet"
echo "  Description: Donate 5000000 XLM to campaign #1"
echo "  Created:     [timestamp]"
echo ""
echo "  Transaction XDR:"
echo "  [XDR_DATA]"
echo ""
echo ""

echo "📝 Example 2: Build a Campaign Creation Request"
echo "=============================================="
echo ""
CREATOR_ADDRESS="GBJCHUKZMTFSLOMNC2P4TS4VJJBTCYL3SDKW3KSMSGQUZ6EFLXVX77JVH"
CAMPAIGN_TITLE="Emergency Relief Fund"
CAMPAIGN_GOAL="1000000000"  # 100 XLM
DEADLINE_TIMESTAMP=$(($(date +%s) + 86400 * 30))  # 30 days from now

echo "Command:"
echo "  stellaraid-cli signing build-campaign \\"
echo "    $CREATOR_ADDRESS \\"
echo "    \"$CAMPAIGN_TITLE\" \\"
echo "    $CAMPAIGN_GOAL \\"
echo "    $DEADLINE_TIMESTAMP"
echo ""
echo ""

echo "📝 Example 3: Validate a Signing Request"
echo "======================================"
echo ""
echo "Command:"
echo "  stellaraid-cli signing validate ./signing_requests/donation_req.json"
echo ""
echo "Expected Output:"
echo "  ✅ Signing request is valid"
echo "  📝 Signing Request"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  [request details]"
echo ""
echo ""

echo "📝 Example 4: Export Request for Wallet"
echo "=================================="
echo ""
echo "Command:"
echo "  stellaraid-cli signing export ./signing_requests/donation_req.json"
echo ""
echo "Expected Output (Freighter-compatible format):"
echo "  📤 Wallet Format:"
echo "  {"
echo "    \"id\":\"req_1234567890000\","
echo "    \"type\":\"tx\","
echo "    \"xdr\":\"AAAAA....\","
echo "    \"network\":\"testnet\","
echo "    \"description\":\"Donate 5000000 XLM to campaign #1\","
echo "    \"timestamp\":1234567890"
echo "  }"
echo ""
echo ""

echo "✅ Example 5: Process Wallet Response"
echo "==================================="
echo ""
echo "Simulated wallet response from Freighter:"
WALLET_RESPONSE='{
  "requestId": "req_1234567890000",
  "xdr": "AAAAAgAAAADDRVZm3Wgf40kMCwbWI6txY5T7PX0J8p5hJF3J+VBDAAAAAAAAA",
  "signer": "GBJCHUKZMTFSLOMNC2P4TS4VJJBTCYL3SDKW3KSMSGQUZ6EFLXVX77JVH",
  "signedAt": 1234567890
}'

echo "Command:"
echo "  stellaraid-cli response process '$WALLET_RESPONSE'"
echo ""
echo "Expected Output:"
echo "  ✅ Transaction Signed Successfully"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Request ID:    req_1234567890000"
echo "  Signer:        GBJCHUKZMTFSLOMNC2P4TS4VJJBTCYL3SDKW3KSMSGQUZ6EFLXVX77JVH"
echo "  Status:        Signed"
echo "  Signed At:     1234567890"
echo ""
echo "  Ready for submission"
echo ""
echo ""

echo "💾 Example 6: Save Signed Transaction"
echo "===================================="
echo ""
echo "Command:"
echo "  stellaraid-cli response save '$WALLET_RESPONSE' ./signed_transactions/donation_signed.json"
echo ""
echo "Expected Output:"
echo "  ✅ Transaction saved to ./signed_transactions/donation_signed.json"
echo "  Request ID: req_1234567890000"
echo ""
echo ""

echo "📂 Example 7: Load Signed Transaction"
echo "==================================="
echo ""
echo "Command:"
echo "  stellaraid-cli response load ./signed_transactions/donation_signed.json"
echo ""
echo "Expected Output:"
echo "  ✅ Transaction loaded from ./signed_transactions/donation_signed.json"
echo ""
echo "  Request ID:    req_1234567890000"
echo "  Signer:        GBJCHUKZMTFSLOMNC2P4TS4VJJBTCYL3SDKW3KSMSGQUZ6EFLXVX77JVH"
echo "  Status:        Signed"
echo "  Signed At:     1234567890"
echo ""
echo "  Transaction XDR:"
echo "  AAAAAgAAAADDRVZm3Wgf40kMCwbWI6txY5T7PX0J8p5hJF3J+VBDAAAAAAAAA"
echo ""
echo ""

echo "✅ Example 8: Validate Signed Transaction"
echo "======================================"
echo ""
echo "Command:"
echo "  stellaraid-cli response validate ./signed_transactions/donation_signed.json"
echo ""
echo "Expected Output:"
echo "  ✅ Transaction is valid"
echo "  Request ID:    req_1234567890000"
echo "  Signer:        GBJCHUKZMTFSLOMNC2P4TS4VJJBTCYL3SDKW3KSMSGQUZ6EFLXVX77JVH"
echo "  Status:        Signed"
echo "  XDR Length:    56 bytes"
echo ""
echo ""

echo "📤 Example 9: Submit Signed Transaction"
echo "======================================"
echo ""
echo "Command:"
echo "  stellaraid-cli response submit ./signed_transactions/donation_signed.json"
echo ""
echo "Expected Output:"
echo "  📤 Submitting Transaction"
echo "  ━━━━━━━━━━━━━━━━━━━━━━"
echo "  Request ID: req_1234567890000"
echo "  Signer:     GBJCHUKZMTFSLOMNC2P4TS4VJJBTCYL3SDKW3KSMSGQUZ6EFLXVX77JVH"
echo ""
echo "  🔄 Sending to Stellar network..."
echo ""
echo "  💡 Full submission implementation coming soon"
echo "     This would submit the signed transaction to:"
echo "     - Validate transaction format"
echo "     - Check sequence numbers"
echo "     - Post to Stellar network"
echo "     - Monitor for confirmation"
echo ""
echo ""

echo "🔄 Complete Signing Workflow"
echo "==========================="
echo ""
echo "The typical workflow is:"
echo ""
echo "1. Backend builds signing request"
echo "   → SigningRequestBuilder creates structured request"
echo "   → TransactionBuilder helps with common transaction types"
echo ""
echo "2. Export to wallet-compatible format"
echo "   → Convert to JSON for transmission to wallet"
echo "   → Include XDR and transaction description"
echo ""
echo "3. User signs in wallet (manual step)"
echo "   → User reviews transaction in Freighter or other wallet"
echo "   → User approves with private key (wallet-side)"
echo "   → Wallet returns signed XDR"
echo ""
echo "4. Process response"
echo "   → ResponseHandler parses wallet response"
echo "   → Validates signer and transaction integrity"
echo "   → Returns ProcessedResponse with validation status"
echo ""
echo "5. Save for later submission"
echo "   → Store signed transaction to file for persistence"
echo "   → Can submit later or batch with other transactions"
echo ""
echo "6. Submit to network"
echo "   → Load signed transaction from file"
echo "   → Submit to Stellar RPC/Horizon"
echo "   → Monitor transaction status"
echo "   → Receive confirmation with transaction hash and ledger"
echo ""
echo ""

echo "🔐 Security Checklist"
echo "===================="
echo ""
echo "✓ Never log private keys or secret signers"
echo "✓ Validate all signer addresses before submission"
echo "✓ Store signed transactions securely before submission"
echo "✓ Always verify correct network (testnet vs mainnet)"
echo "✓ Check transaction fees match expectations"
echo "✓ Validate response sources when integrating wallets"
echo "✓ Use HTTPS for all wallet communication"
echo "✓ Implement request rate limiting for security"
echo ""
echo ""

echo "✨ Setup Complete!"
echo ""
echo "You can now use the signing request and response handler"
echo "for building and processing Stellar transactions."
echo ""
echo "For more information, see: SIGNING_REQUEST_GUIDE.md"
