[contract]
name = "stellaraid-core"
version = "0.1.0"

[networks.testnet]
rpc_url = "https://soroban-testnet.stellar.org:443"
network_passphrase = "Test SDF Network ; September 2015"

[networks.mainnet]
rpc_url = "https://soroban-rpc.mainnet.stellar.gateway.fm"
network_passphrase = "Public Global Stellar Network ; September 2015"

[networks.sandbox]
rpc_url = "http://localhost:8000"
network_passphrase = "Stellar Sandbox Network"
